[phases.setup]
nixPkgs = ["nodejs_latest", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm build", "mkdir -p dist", "cp -r server dist/", "cp -r drizzle dist/", "cp -r storage dist/", "cp -r shared dist/"]

[start]
cmd = "pnpm start"
